### ISSUE TITLE
remove `fix_path` from `devel` branch

### ISSUE THREAD

**Issue by jmlondon** [NMML/crawl#40]
in prep for `crawl` freeze and final release, I think it is best to remove the `fix_path` functions and put these into separate branches that will be available here in github. The current `fix_path` approach is unstable and may not work consistently. I'd also suggest another branch with the **old** `fix_path` approach.

**Comment by jmlondon** [comment]
@dsjohnson is working on this in #45

**Comment by dsjohnson** [comment]
new issue added with master as well
