### ISSUE TITLE
Specifying error model from acoustic telemetry

### ISSUE THREAD

**Issue by DEHewitt** [NMML/crawl#42]
Hi,

I am attempting to use your package, as the first step in the two-stage momentuHMM analysis, to predict temporally regular locations of crabs within a VPS. My question is related to the error model: I have data on the error in this system obtained from stationary tags deployed throughout the study period, would it be proper use of the function `argosDiag2Cov()` to provide vectors of these x and y errors (in metres) to the `Major` and `Minor` arguments and use the mean of the output as `ln.sd.x` and `ln.sd.y` in the call to `err.model`? Holding aside the consideration of whether or not error obtained from stationary tags is similar to the error from tags on animals.

Thanks for any help you can provide!

**Comment by dsjohnson** [comment]
I don't think you need the Argos diagnostic function. Do all the locations have the same error rate? e.g., with Argos, there are different error classes. If so, I would calculate the SD of the x and y deviations as well as the correlation in the x and y deviations. Then take the log (not of the correlation though). Then these can be used in place of the ln.sd.x and ln.sd.y and rho.

**Comment by DEHewitt** [comment]
Thanks again for your response here @dsjohnson. I have finally gotten around to writing this work up. This isn't really an issue with the package per se, but I was hoping for some advice of how I could succinctly express this in-text. I don't want to provide a full mathematical description, rather just a line or two explaining the process. I have the following so far:

"_... we first predicted temporally regular locations at 15-minute intervals by modelling crab movement as a continuous-time correlated random walk using the R package ‘crawl’ (Johnson and London, 2018). We refer readers to Johnson et al. (2008) for a full mathematical description of this model. Using this model, locations are estimated in a state-space framework, thereby allowing the inclusion of measurement error in location estimates. This was a chieved by transforming the error (in m) in both axes (longitudinal and latitudinal), derived from the two fixed-position reference tags, into a covariance matrix and approximating it with a bivariate Gaussian distribution (Johnson et al., 2008)._" 

Is this suitable?

Thanks again for your help!

**Comment by dsjohnson** [comment]
Looks good to me. I would probably write "...  locations are estimated *using* a state-space framework"
