### ISSUE TITLE
setting a period of non-movement in crawl

### ISSUE THREAD

**Issue by MarkJThomas** [NMML/crawl#57]
Hi,
I have GPS data recorded from 5am - 7pm (with some gaps in the daytime) to run HMM models the data needs to be complete (GPS points for 24hrs). We know the animal doesn't move at night, is there a way to incorporate that into the model? 
So 7pm - 5am = non-movement, then the model can fill in any gaps during the day.
All the best,
Mark

**Comment by dsjohnson** [comment]
Hi Mark,
Just add some augmented times at, say, 7:01p and 4:59a everyday. Then add an "activity" column which is an indicator column with 1s for times prior to 7:01p, a 0 for 7:01p and times prior to 4:59a, 1s for time = 4:59a,... Then use the activity argument in crwMLE(). See the harbor seal example in: https://www.researchgate.net/profile/Devin-Johnson-4/publication/5312896_Continuous-time_correlated_random_walk_model_for_animal_telemetry_data/links/5bfed604a6fdcc1b8d49ec44/Continuous-time-correlated-random-walk-model-for-animal-telemetry-data.pdf
