### ISSUE TITLE
batch version of crwPredict and crwMLE

### ISSUE THREAD

**Issue by dsjohnson** [NMML/crawl#6]

**Comment by jmlondon** [comment]
I think @dsjohnson can go ahead and close this as I'm not sure we need this any more. The bearded seal example in the vignette (SHA: 51e85d9093208de636458895f1cbf5f27cfbe28b) includes code that uses the foreach/doParallel packages for crwMLE() and crwPredict. Not sure we need additional functionality beyond this.

**Comment by dsjohnson** [comment]
Closed
